//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientSumator.SumatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SumatorServiceReference.IServiceSumator")]
    public interface IServiceSumator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSumator/Sum", ReplyAction="http://tempuri.org/IServiceSumator/SumResponse")]
        long Sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSumator/Sum", ReplyAction="http://tempuri.org/IServiceSumator/SumResponse")]
        System.Threading.Tasks.Task<long> SumAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSumatorChannel : WcfClientSumator.SumatorServiceReference.IServiceSumator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSumatorClient : System.ServiceModel.ClientBase<WcfClientSumator.SumatorServiceReference.IServiceSumator>, WcfClientSumator.SumatorServiceReference.IServiceSumator {
        
        public ServiceSumatorClient() {
        }
        
        public ServiceSumatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSumatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSumatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSumatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long Sum(int a, int b) {
            return base.Channel.Sum(a, b);
        }
        
        public System.Threading.Tasks.Task<long> SumAsync(int a, int b) {
            return base.Channel.SumAsync(a, b);
        }
    }
}
